### ISSUE TITLE
Explicitly globalize implicit global `segment_base_info` (or localize it)

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-userlike#1]
@thomassittig, Looks like the following LOC declares an implicit a global:

https://github.com/segment-integrations/analytics.js-integration-userlike/blob/master/lib/index.js#L46-L52

Should this be a global, or should it actually be a global? If it's meant to be a global we should define it explicitly (e.g. `window.segment_base_info`).

**Comment by hankim813** [comment]
Closed for inactivity/irrelevance. Please reopen if it's still an issue!
